In [3]:
!pip install pandas pyarrow

Looking in indexes: https://ship-nexus.maestro.gov.sg/repository/pypi-proxy/simple/
Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: pyarrow in /opt/conda/lib/python3.12/site-packages (21.0.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd
import pyarrow

# Offline Chunking

simple_preprocess.py → Character-based, offline

- Has built-in simple_chunk_by_chars() function
- Works completely offline, no external dependencies
- Simpler but cuts mid-word/sentence

In [28]:
df = pd.read_parquet("../out/articles.parquet")
df.head(1)

,title,url,news_site,published_date,quarter_year,content,topic,sentiment_score,explanation,year,article_id_key,article_topic_key
0,"19,600 BTO flats to launch this year, includin...",https://www.channelnewsasia.com/singapore/1960...,cna,2025-01-16 17:00:00,2025Q1,Flats with shorter waiting times will become “...,"BTO & SBF Supply, Launches, and Demand",0.8,The article discusses increased BTO supply and...,2025,"19,600 BTO flats to launch this year, includin...","19,600 BTO flats to launch this year, includin..."

## Chunks

In [10]:
chunks = pd.read_parquet("../out/semantic_chunks.parquet")
chunks.head(1)

,article_id_key,article_topic_key,chunk_id,title,topic,year,quarter_year,news_site,published_date,sentiment_score,explanation,content_chunk,retrieval_text
0,"19,600 BTO flats to launch this year, includin...","19,600 BTO flats to launch this year, includin...",0,"19,600 BTO flats to launch this year, includin...","BTO & SBF Supply, Launches, and Demand",2025,2025Q1,cna,2025-01-16 17:00:00,0.8,The article discusses increased BTO supply and...,Flats with shorter waiting times will become “...,"Title: 19,600 BTO flats to launch this year, i..."

In [24]:
print(chunks['content_chunk'].iloc[0])

Flats with shorter waiting times will become “a major feature” of Singapore’s upcoming flat supply, says Minister for National Development Desmond Lee. SINGAPORE: About 19,600 Build-to-Order (BTO) flats will be launched in 2025, as part of the government's efforts to boost public housing supply and meet rising demand. Among them, 3,800 flats – or nearly 20 per cent – will have shorter waiting times of under three years, said Minister for National Development Desmond Lee in an interview with CNA Digital, the Straits Times and Lianhe Zaobao earlier this week. In addition, the Housing Board plans to offermore than 5,500 units in February via its largest-ever Sale of Balance Flats exercise. This brings the total number of flats for sale this year to over 25,000. The flats will includeStandard, Plus and Prime flats – the three categories under arevised classification framework– in locations such as Kallang/Whampoa, Bukit Merah, Queenstown, Mount Pleasant, Woodlands, Yishun and Sembawang. With this year's offering, the government is on track to launch about 102,300 BTO flats between 2021 and 2025, exceeding its earlier commitment of 100,000 units over the five-year period, said Mr Lee. “We have ramped up supply quite dramatically,” he told reporters. He added that the government's next target is to launch 130,000 new flats by 2027, which means another 30,000 flats can be expected to go on sale in the next two years. TACKLING PANDEMIC-INDUCED CHALLENGES This increased housing supply addresses challenges brought on by the COVID-19 pandemic, which disrupted construction, materials and labour, causing delays in BTO completions. At the same time, demand surged due to demographic shifts and pandemic-related factors, driving up resale prices after years of stagnation. Almost five years on, Mr Lee said the government has resolved many of these issues, including clearingthe backlog of delayed projects. The last batch of pandemic-delayed flats will be handed over to home owners within weeks, he said. The ramp-up in supply has also lowered the average application rate for first-time buyers. Across all flat types, the rate fell to 2.1 in 2024 from 3.7 in 2019. For three-room and larger flats, the rate dropped to 2.2 from 4.0 in the same period. More flats with shorter waiting times are being offered, rising from 732 in 2023 to 2,876 in 2024 and 3,800 this year. While this is becoming a "major feature" of the BTO supply, Mr Lee cautioned that availability will depend on land resources and application rate trends. To address housing affordability amid rising resale prices, the government has introduced cooling measures and enhanced grants for first-time buyers. He said the government is “not averse to putting in new measures” to ensure that the property market stays aligned with economic fundamentals. But it must consider the cooling measures that are still working their way through the market, the significant housing supply that will eventually come on stream, as well as uncertainties in the global economic and geopolitical environment. CHANGES COMING UP In the year ahead, Mr Lee said the government is committed to initiatives to accommodate singles. Starting mid-2025, singles will be included in schemes thatprioritise those applying for flats to live with or near family. The new Family Care Scheme (FCS) will berolled out in two phasesto replace the existing schemes that reserve priority access for married couples and their parents. “We expect this will be a second driver in demand from singles and that's why we are committed to launching more two-room flats,” the minister said. Additionally, more two-room flats will be offered, with one in four units in February's launch catering to the growing demand from singles. February’s BTO exercise will also see a reduction in queue numbers issued – from three times to two times the number of flats available – due to a decline in applicants failing to select a flat. The introduction ofstricter penaltiesi

In [26]:
print(chunks['retrieval_text'].iloc[0])

Title: 19,600 BTO flats to launch this year, including 3,800 units with waiting time of under 3 years
Topic: BTO & SBF Supply, Launches, and Demand
Published date: 2025-01-16 17:00:00
Year: 2025
News site: cna
Sentiment score: 0.8
Topic sentiment explanation: The article discusses increased BTO supply and launches, with positive sentiment towards addressing housing demand and reducing waiting times.

Content:
Flats with shorter waiting times will become “a major feature” of Singapore’s upcoming flat supply, says Minister for National Development Desmond Lee. SINGAPORE: About 19,600 Build-to-Order (BTO) flats will be launched in 2025, as part of the government's efforts to boost public housing supply and meet rising demand. Among them, 3,800 flats – or nearly 20 per cent – will have shorter waiting times of under three years, said Minister for National Development Desmond Lee in an interview with CNA Digital, the Straits Times and Lianhe Zaobao earlier this week. In addition, the Housing Board plans to offermore than 5,500 units in February via its largest-ever Sale of Balance Flats exercise. This brings the total number of flats for sale this year to over 25,000. The flats will includeStandard, Plus and Prime flats – the three categories under arevised classification framework– in locations such as Kallang/Whampoa, Bukit Merah, Queenstown, Mount Pleasant, Woodlands, Yishun and Sembawang. With this year's offering, the government is on track to launch about 102,300 BTO flats between 2021 and 2025, exceeding its earlier commitment of 100,000 units over the five-year period, said Mr Lee. “We have ramped up supply quite dramatically,” he told reporters. He added that the government's next target is to launch 130,000 new flats by 2027, which means another 30,000 flats can be expected to go on sale in the next two years. TACKLING PANDEMIC-INDUCED CHALLENGES This increased housing supply addresses challenges brought on by the COVID-19 pandemic, which disrupted construction, materials and labour, causing delays in BTO completions. At the same time, demand surged due to demographic shifts and pandemic-related factors, driving up resale prices after years of stagnation. Almost five years on, Mr Lee said the government has resolved many of these issues, including clearingthe backlog of delayed projects. The last batch of pandemic-delayed flats will be handed over to home owners within weeks, he said. The ramp-up in supply has also lowered the average application rate for first-time buyers. Across all flat types, the rate fell to 2.1 in 2024 from 3.7 in 2019. For three-room and larger flats, the rate dropped to 2.2 from 4.0 in the same period. More flats with shorter waiting times are being offered, rising from 732 in 2023 to 2,876 in 2024 and 3,800 this year. While this is becoming a "major feature" of the BTO supply, Mr Lee cautioned that availability will depend on land resources and application rate trends. To address housing affordability amid rising resale prices, the government has introduced cooling measures and enhanced grants for first-time buyers. He said the government is “not averse to putting in new measures” to ensure that the property market stays aligned with economic fundamentals. But it must consider the cooling measures that are still working their way through the market, the significant housing supply that will eventually come on stream, as well as uncertainties in the global economic and geopolitical environment. CHANGES COMING UP In the year ahead, Mr Lee said the government is committed to initiatives to accommodate singles. Starting mid-2025, singles will be included in schemes thatprioritise those applying for flats to live with or near family. The new Family Care Scheme (FCS) will berolled out in two phasesto replace the existing schemes that reserve priority access for married couples and their parents. “We expect this will be a second driver in demand from singles and that's why we are committed to launching more two-room flats,” the minister said. Additionally, more two-room flats will be offered, with one in four units in February's launch catering to the growing demand from singles. February’s BTO exercise will also see a reduction in queue numbers issued – from three times to two times the number of flats available – due to a decline in applicants failing to select a flat. The introduction ofstricter penaltiesi

# Token aware chunking

preprocess.py → Sentence-aware + tiktoken

- Uses semantic_chunks.py → calls token_chunking.py → requires tiktoken
- Smart chunking (respects sentences, accurate token counts)
- Need to downloac tiktoken beforehand

In [30]:
chunks = pd.read_parquet("../out2/semantic_chunks.parquet")
chunks.head(1)

,article_id_key,article_topic_key,chunk_id,title,topic,year,quarter_year,news_site,published_date,sentiment_score,explanation,content_chunk,retrieval_text,chunk_token_count,retrieval_token_count
0,"19,600 BTO flats to launch this year, includin...","19,600 BTO flats to launch this year, includin...",0,"19,600 BTO flats to launch this year, includin...","BTO & SBF Supply, Launches, and Demand",2025,2025Q1,cna,2025-01-16 17:00:00,0.8,The article discusses increased BTO supply and...,Flats with shorter waiting times will become “...,"Title: 19,600 BTO flats to launch this year, i...",726,830

In [31]:
print(chunks['content_chunk'].iloc[0])

Flats with shorter waiting times will become “a major feature” of Singapore’s upcoming flat supply, says Minister for National Development Desmond Lee. SINGAPORE: About 19,600 Build-to-Order (BTO) flats will be launched in 2025, as part of the government's efforts to boost public housing supply and meet rising demand. Among them, 3,800 flats – or nearly 20 per cent – will have shorter waiting times of under three years, said Minister for National Development Desmond Lee in an interview with CNA Digital, the Straits Times and Lianhe Zaobao earlier this week. In addition, the Housing Board plans to offermore than 5,500 units in February via its largest-ever Sale of Balance Flats exercise. This brings the total number of flats for sale this year to over 25,000. The flats will includeStandard, Plus and Prime flats – the three categories under arevised classification framework– in locations such as Kallang/Whampoa, Bukit Merah, Queenstown, Mount Pleasant, Woodlands, Yishun and Sembawang. With this year's offering, the government is on track to launch about 102,300 BTO flats between 2021 and 2025, exceeding its earlier commitment of 100,000 units over the five-year period, said Mr Lee. “We have ramped up supply quite dramatically,” he told reporters. He added that the government's next target is to launch 130,000 new flats by 2027, which means another 30,000 flats can be expected to go on sale in the next two years. TACKLING PANDEMIC-INDUCED CHALLENGES This increased housing supply addresses challenges brought on by the COVID-19 pandemic, which disrupted construction, materials and labour, causing delays in BTO completions. At the same time, demand surged due to demographic shifts and pandemic-related factors, driving up resale prices after years of stagnation. Almost five years on, Mr Lee said the government has resolved many of these issues, including clearingthe backlog of delayed projects. The last batch of pandemic-delayed flats will be handed over to home owners within weeks, he said. The ramp-up in supply has also lowered the average application rate for first-time buyers. Across all flat types, the rate fell to 2.1 in 2024 from 3.7 in 2019. For three-room and larger flats, the rate dropped to 2.2 from 4.0 in the same period. More flats with shorter waiting times are being offered, rising from 732 in 2023 to 2,876 in 2024 and 3,800 this year. While this is becoming a "major feature" of the BTO supply, Mr Lee cautioned that availability will depend on land resources and application rate trends. To address housing affordability amid rising resale prices, the government has introduced cooling measures and enhanced grants for first-time buyers. He said the government is “not averse to putting in new measures” to ensure that the property market stays aligned with economic fundamentals. But it must consider the cooling measures that are still working their way through the market, the significant housing supply that will eventually come on stream, as well as uncertainties in the global economic and geopolitical environment. CHANGES COMING UP In the year ahead, Mr Lee said the government is committed to initiatives to accommodate singles. Starting mid-2025, singles will be included in schemes thatprioritise those applying for flats to live with or near family.

In [32]:
print(chunks['retrieval_text'].iloc[0])

Title: 19,600 BTO flats to launch this year, including 3,800 units with waiting time of under 3 years
Topic: BTO & SBF Supply, Launches, and Demand
Published date: 2025-01-16
Year: 2025
News site: cna
Sentiment score: 0.8
Topic sentiment explanation: The article discusses increased BTO supply and launches, with positive sentiment towards addressing housing demand and reducing waiting times.

Content:
Flats with shorter waiting times will become “a major feature” of Singapore’s upcoming flat supply, says Minister for National Development Desmond Lee. SINGAPORE: About 19,600 Build-to-Order (BTO) flats will be launched in 2025, as part of the government's efforts to boost public housing supply and meet rising demand. Among them, 3,800 flats – or nearly 20 per cent – will have shorter waiting times of under three years, said Minister for National Development Desmond Lee in an interview with CNA Digital, the Straits Times and Lianhe Zaobao earlier this week. In addition, the Housing Board plans to offermore than 5,500 units in February via its largest-ever Sale of Balance Flats exercise. This brings the total number of flats for sale this year to over 25,000. The flats will includeStandard, Plus and Prime flats – the three categories under arevised classification framework– in locations such as Kallang/Whampoa, Bukit Merah, Queenstown, Mount Pleasant, Woodlands, Yishun and Sembawang. With this year's offering, the government is on track to launch about 102,300 BTO flats between 2021 and 2025, exceeding its earlier commitment of 100,000 units over the five-year period, said Mr Lee. “We have ramped up supply quite dramatically,” he told reporters. He added that the government's next target is to launch 130,000 new flats by 2027, which means another 30,000 flats can be expected to go on sale in the next two years. TACKLING PANDEMIC-INDUCED CHALLENGES This increased housing supply addresses challenges brought on by the COVID-19 pandemic, which disrupted construction, materials and labour, causing delays in BTO completions. At the same time, demand surged due to demographic shifts and pandemic-related factors, driving up resale prices after years of stagnation. Almost five years on, Mr Lee said the government has resolved many of these issues, including clearingthe backlog of delayed projects. The last batch of pandemic-delayed flats will be handed over to home owners within weeks, he said. The ramp-up in supply has also lowered the average application rate for first-time buyers. Across all flat types, the rate fell to 2.1 in 2024 from 3.7 in 2019. For three-room and larger flats, the rate dropped to 2.2 from 4.0 in the same period. More flats with shorter waiting times are being offered, rising from 732 in 2023 to 2,876 in 2024 and 3,800 this year. While this is becoming a "major feature" of the BTO supply, Mr Lee cautioned that availability will depend on land resources and application rate trends. To address housing affordability amid rising resale prices, the government has introduced cooling measures and enhanced grants for first-time buyers. He said the government is “not averse to putting in new measures” to ensure that the property market stays aligned with economic fundamentals. But it must consider the cooling measures that are still working their way through the market, the significant housing supply that will eventually come on stream, as well as uncertainties in the global economic and geopolitical environment. CHANGES COMING UP In the year ahead, Mr Lee said the government is committed to initiatives to accommodate singles. Starting mid-2025, singles will be included in schemes thatprioritise those applying for flats to live with or near family.